### PR TITLE
Add ScrollView to Main Screen UI

### PR DESCRIPTION
**Pull request by noobshubham**
- Added a ScrollView component to the main screen's layout.
- It fixes the issue #5

### CODE REVIEW

**Comment by AzeemIdrisi** [comment]
You are trying to solve a non-existing problem. I just rechecked the current version, and it has no issues moving back and forth around the entered text, even if it is pretty long.

Thank you for making an effort to make this app better, but this change does not solve any problems.

**Comment by noobshubham** [comment]
Actually description and title got wrong, I was trying to solve the page
scrollable while entering the username. And everything is right

**Comment by noobshubham** [comment]
Okay, fine!

**Comment by AzeemIdrisi** [comment]
Great work, The app looks better now.
Thank you for making this contribution.
Do you want hacktoberfest-accepted label?

**Comment by AzeemIdrisi** [comment]
@noobshubham I want you to delete the [u: Local Chaquopy Setup](https://github.com/AzeemIdrisi/InstaLoaderApp/pull/6/commits/4e2acd53eb0fbe2a8850e5465f9c2997b0dd0c84) commit from the pull request leaving only the main change in the pull request.

**Review by AzeemIdrisi — CHANGES_REQUESTED** [review]
Remove this commit.

**Comment by noobshubham** [comment]
Yes, I wanted the label.
Thanks.

**Comment by noobshubham** [comment]
Yes, it's done. Thanks!

**Comment by noobshubham** [comment]
Hey sorry man, I wasn't able to delete that local setup today. I'll surely
do it by tomorrow and let you know. Thanks.

**Comment by noobshubham** [comment]
> @noobshubham I want you to delete the [u: Local Chaquopy Setup](https://github.com/AzeemIdrisi/InstaLoaderApp/pull/6/commits/4e2acd53eb0fbe2a8850e5465f9c2997b0dd0c84) commit from the pull request leaving only the main change in the pull request.

Can you please help me with the command, I don't understand what should I use like revert or rebase.

**Comment by AzeemIdrisi** [comment]
Try this : https://stackoverflow.com/a/51400593

**Comment by noobshubham** [comment]
> Try this : https://stackoverflow.com/a/51400593

Done, Thanks Alot.

**Pull request merged**
